### ISSUE TITLE
How do I use this?

### ISSUE THREAD

**Issue by alexmccabe** [supercrabtree/hyperterm-dibdabs#1]
I like the idea of this, but how do I use it?

**Comment by wkurosawa** [comment]
@alexmccabe you just need to add to your `plugins` array on your hyperterm config file. 
Then it will create a dot with color based on a hash from folder name. 

It will only add the dot if there is tabs.

**Comment by alxvallejo** [comment]
```
Uncaught Exception:
.hyper.js:177
hyperterm - dibdabs,
^

ReferenceError: hyperterm is not defined
at .hyper.js:177:5
at Script.runInContext (node:vm:139:12)
at Script.runInNewContext (node:vm:144:17)
at _extract (/Applications/Hyper.app/Contents/Resources/app.asar/config/init.js:12:13)
at _init (/Applications/Hyper.app/Contents/Resources/app.asar/config/init.js:35:28)
at _import (/Applications/Hyper.app/Contents/Resources/app.asar/config/import.js:113:37)
at Timeout._onTimeout (/Applications/Hyper.app/Contents/Resources/app.asar/config.js:46:40)
at listOnTimeout (node:internal/timers:559:17)
at process.processTimers (node:internal/timers:502:7)
```
